version: '3.4'

services:
  easyclinic.authservice.api:
    image: ${DOCKER_REGISTRY-}easyclinic-authservice-api
    container_name: easyclinic.authservice.api
    build:
      context: .
      dockerfile: src/AuthService/EasyClinic.AuthService.Api/Dockerfile

  easyclinic.authservice.db:
    image: postgres:16-alpine
    ports:
      - "61002:5432"
    restart: always
    volumes:
      - authservice_data:/var/lib/postgresql/data

volumes:
  authservice_data:

